insert into category_product (description) values ('Cardiovascular Health');
insert into category_product (description) values ('Pain Relief');
insert into category_product (description) values ('Respiratory Health');
insert into category_product (description) values ('Gastrointestinal Health');
insert into category_product (description) values ('Endocrine System');
insert into category_product (description) values ('Infectious Diseases');
insert into category_product (description) values ('Central Nervous System');
insert into category_product (description) values ('Musculoskeletal Health');
insert into category_product (description) values ('Dermatological Products');
insert into category_product (description) values ('Vitamins and Supplements');
insert into category_product (description) values ('Women''s Health');
insert into category_product (description) values ('Eye and Ear Care');
insert into category_product (description) values ('First Aid Supplies');
insert into category_product (description) values ('Oral Health');
insert into category_product (description) values ('Medical Devices');
insert into category_product (description) values ('Home Health Care');
